package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"errors"
	"fmt"
	"mihirgql/graph/helpers"
	"mihirgql/graph/model"

	"github.com/google/uuid"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.UserInputField) (*model.User, error) {
	userId := uuid.New()

	isUser := helpers.GetUserByName(input.Username, r.users)
	if isUser {
		return nil, errors.New("user already exists")
	}

	user := model.User{
		ID:       userId.String(),
		Username: input.Username,
		Password: input.Password,
	}
	r.users = append(r.users, &user)

	return &user, nil
}

// CreatePlaylist is the resolver for the createPlaylist field.
func (r *mutationResolver) CreatePlaylist(ctx context.Context, input model.PlaylistInputField) (*model.Playlist, error) {
	playlistId := uuid.New()
	musics := []*model.Music{}

	for _, mId := range input.MusicIds {
		m, err := helpers.FindById(mId, r.musics)
		if err != nil {
			return nil, err
		}
		fmt.Println(m)
		fmt.Println(mId)

		musics = append(musics, m)
	}

	user, err := helpers.FindById(input.Author, r.users)
	if err != nil {
		return nil, err
	}

	playlist := model.Playlist{
		ID:           playlistId.String(),
		PlaylistName: input.PlaylistName,
		Musics:       musics,
		Author:       user,
	}

	r.playlists = append(r.playlists, &playlist)

	return &playlist, nil
}

// CreateMusic is the resolver for the createMusic field.
func (r *mutationResolver) CreateMusic(ctx context.Context, input model.MusicInputField) (*model.Music, error) {
	musicId := uuid.New()

	user, err := helpers.FindById(input.Artist, r.users)
	if err != nil {
		return nil, errors.New("artist/user doesn't exists")
	}

	music := model.Music{
		ID:     musicId.String(),
		Name:   input.Name,
		Len:    input.Len,
		Artist: user,
	}

	r.musics = append(r.musics, &music)

	return &music, nil
}

// Playlists is the resolver for the playlists field.
func (r *queryResolver) Playlists(ctx context.Context) ([]*model.Playlist, error) {
	return r.playlists, nil
}

// Playlist is the resolver for the playlist field.
func (r *queryResolver) Playlist(ctx context.Context, id string) (*model.Playlist, error) {
	playlist, err := helpers.FindById(id, r.playlists)
	if err != nil {
		return nil, errors.New("error finding the playlist")
	}

	return playlist, nil
}

// Musics is the resolver for the musics field.
func (r *queryResolver) Musics(ctx context.Context) ([]*model.Music, error) {
	return r.musics, nil
}

// Music is the resolver for the music field.
func (r *queryResolver) Music(ctx context.Context, id string) (*model.Music, error) {
	music, err := helpers.FindById(id, r.musics)
	if err != nil {
		return nil, errors.New("error finding the song")
	}

	return music, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
