// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Music struct {
	ID     string `json:"id"`
	Artist *User  `json:"artist"`
	Len    string `json:"len"`
	Name   string `json:"name"`
}

type MusicInputField struct {
	Artist string `json:"artist"`
	Len    string `json:"len"`
	Name   string `json:"name"`
}

type Mutation struct {
}

type Playlist struct {
	ID           string   `json:"id"`
	PlaylistName string   `json:"playlistName"`
	Musics       []*Music `json:"musics"`
	Author       *User    `json:"author"`
}

type PlaylistInputField struct {
	PlaylistName string   `json:"playlistName"`
	Author       string   `json:"author"`
	MusicIds     []string `json:"musicIds"`
}

type Query struct {
}

type User struct {
	ID        string      `json:"id"`
	Username  string      `json:"username"`
	Password  string      `json:"password"`
	Playlists []*Playlist `json:"playlists,omitempty"`
	Musics    []*Music    `json:"musics,omitempty"`
}

type UserInputField struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
